---
- hosts: all
  become: yes
  tasks:
    - name: Exécuter une commande pour récupérer une donnée
      shell: cat /home/filigran/test.yml  # Commande pour récupérer la donnée
      register: output  # Enregistrer la sortie de la commande dans une variable

    - name: Afficher la sortie de la commande
      debug:
        var: output.stdout
