---
mysql_password: tokilechat
mysql_socket: /var/run/mysqld/mysqld.sock
mysql_db_name: Bikini_Bottom

mysql_users: 
  - name: bob
    password: "bobbobby"
    priv: 'Bikini_Bottom.*:ALL'
  - name: toto
    password: "totototo"
    priv: '*.*:ALL'
  - name: titi
    password: "titititi"
    priv: 'Bikini_Bottom.*:ALL'