name: Ansible arborescence deployement
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 
            ansible 
             .ansible.cfg
          path: 
            ansible/ 
            .ansible.cfg

      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          path: .
          name: 
            ansible 
            .ansible.cfg
          
      - name: execute
        run: |    
          cd ansible/playbooks
          ansible-playbook ./recette-apache.yml
          ansible-playbook ./recette-mysql.yml
          

      
        
