name: Ansible arborescence deployement
on: [push]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create arborescence
        run: |
          cp -R ansible/ /home/student
          cp .ansible.cfg /home/student
          
      - name: execute
        run: |    
          cd ansible/playbooks
          ansible-playbook ./recette-apache.yml
          ansible-playbook ./recette-mysql.yml
          

      
        
